
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/intern_2024
    username: root
    password: abcd@1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect